/// @description Insert description here
// You can write your code in this editor

x		=	xstart;
y		=	ystart;

with (other)	{
	x	=	xstart;
	y	=	ystart;
}

show_message(" Early humans used milk to teach us how to survive; they used milk as a source of food and a way to guard against illness. In addition, milk was an integral part of early cultures. The milk of mother cows became the food source for newborn babies and other animals. In addition, humans used milk as a food source for themselves. However, in recent years, scientists have found that the overuse of milk has caused health problems in humans. Through understanding our past consumption habits, we now know that milk is not always healthy for us.");
show_message(" Most people agree that milk is healthy and necessary for your body; however, some believe it is not healthy at all. We have known for years that dairy products are good for us because mothers have been feeding their children this food source since ancient times. The manufacturing industry of countries like India and China has taken advantage of this knowledge to create high-quality dairy products for export markets. As a result, these countries supply most international restaurants with dairy dishes as staples in their menus. Consequently, these restaurants can produce more money as they sell more meals to customers who eat based on recommendations from their doctors. ");
show_message("Early humans used milk to teach us how to survive; they used milk as a source of food and a way to guard against illness. In addition, milk was an integral part of early cultures. The milk of mother cows became the food source for newborn babies and other animals. In addition, humans used milk as a food source for themselves. However, in recent years, scientists have found that the overuse of milk has caused health problems in humans when consumed excessively (1). This includes problems such as obesity, diabetes, heart disease and certain types of cancer— conditions which are on the rise in the West today (2). To combat these illnesses early on when they first appear in society, our governments now recommend we limit our intake of dairy products (3). Instead of causing medical problems later on in life like modern-day animals did back then, early humans were taught how to eat too much dairy by accident early on in life until their bodies knew enough! ");
show_message("In addition: Over generations — this can take several decades or even longer! — early humans learned how to make better choices with their diet by limiting their consumption of dairy products until they learned how healthy it really was for them (4). Once they knew enough about their diet’s effect on their bodies’ wellness level (i.e., ), these early humans began incorporating other foods into their diets instead of eating only foods containing animal protein or animal fat isolated from animals or animal by-products such as cheese or butterfat (5). These new foods included fruits— which had been eaten by apes since the time apes lived with modern-day primates 60 million years ago— into their diet along with grains such as breads made from wheat or spelt wheat called “farina” (from Latin “farina”) along with beans or pulses such as lentils called “lentil soup” (from Latin “lenticula”). This way — this slow transition from eating solely animal protein foods — allowed our ancestors an opportunity to learn enough about what they were eating so that they could make good choices for themselves!");
show_message("A new human is taught when he learns about the importance of being an integral part 1/6th part) part) ");
show_message(" Early humankind was eating animal proteins before learning how to make better choices through trial and error through consuming dairy products like mother cows did at first sight since prehistoric times! When humankind began making these accidental discoveries several centuries later along with recognizing them as God intended them to be known — there were no accidents then but rather learning curves at different paces — life changed forever! We now know that if we don’t watch what we eat — we can easily become sick if we overindulge ourselves like ancient animals did before learning how not");